[boot]
systemd=true

[automount]
enabled=true
mountFsTab=true
options=metadata,umask=022,fmask=011

[network]
hostname=worker-4070ti-wsl
generateHosts=true
generateResolvConf=true

[interop]
enabled=true
appendWindowsPath=false

[user]
default=gpucontrol
