from __future__ import annotations

import json
import logging
import uuid
from typing import Any, Callable

from assetclaw_matting.skills import (
    bot_skills,
    file_skills,
    file_extra_skills,
    future_skills,
    life_skills,
    matting_skills,
    media_skills,
    memory_skills,
    matting_pipeline_skills,
    agent_ops_skills,
    animation_flow_skills,
    animation_ops_skills,
    custom_pipeline_skills,
    comfyui_skills,
    cherry_skills,
    direct_image_skills,
    direct_video_skills,
    emotion_skills,
    feishu_table_skills,
    frame_skills,
    p4_skills,
    shared_matting_skills,
    speech_skills,
    sticker_skills,
    web_skills,
    workspace_skills,
    queue_skills,
    status_skills,
    text_skills,
    translation_skills,
    utility_skills,
    unity_ready_skills,
    unity_import_skills,
    unity_tools_skills,
)
from assetclaw_matting.skills.security import redact_secrets

log = logging.getLogger(__name__)

_ALLOWED_ROOTS = [
    "D:\\",
    "E:\\",
    "F:\\",
    "Z:\\",
    "C:\\Users\\lilithgames\\Downloads\\ComfyUI-aki-v3",
    r"\\audioshare.lilith.com\AIart\公共机共享\抠图",
]
_DENY_PATTERNS = [".env", ".ssh", "AppData", "Windows", "Program Files", "ProgramData", "$Recycle.Bin", "System Volume Information"]


def _skill(
    name: str,
    description: str,
    implemented: bool,
    fn: Callable[..., dict[str, Any]],
    parameters: dict[str, Any] | None = None,
    partial: bool = False,
    domain: str = "other",
    risk_level: str = "readonly",
    requires_confirmation: bool = False,
    examples: list[dict] | None = None,
    natural_language_examples: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "name": name,
        "domain": domain,
        "description": description,
        "implemented": implemented,
        "partial": partial,
        "risk_level": risk_level,
        "requires_confirmation": requires_confirmation,
        "parameters": parameters or {},
        "allowed_roots": _ALLOWED_ROOTS,
        "deny_patterns": _DENY_PATTERNS,
        "examples": examples or [],
        "natural_language_examples": natural_language_examples or [],
        "fn": fn,
    }


SKILLS: list[dict[str, Any]] = [
    # ---- bot/system skills ------------------------------------------------
    _skill(
        "bot.help",
        "Show bot capabilities, usage examples, and current limitations.",
        True,
        bot_skills.bot_help,
        {},
        domain="bot",
        risk_level="readonly",
        natural_language_examples=["你会做什么", "帮助", "help", "怎么用", "使用说明"],
    ),
    _skill(
        "bot.skills",
        "List all registered skills with their status and risk level.",
        True,
        bot_skills.bot_skills,
        {},
        domain="bot",
        risk_level="readonly",
        natural_language_examples=["查看技能列表", "技能列表", "skill list"],
    ),
    _skill(
        "bot.permissions",
        "Show allowed paths, denied patterns, and security boundaries.",
        True,
        bot_skills.bot_permissions,
        {},
        domain="bot",
        risk_level="readonly",
        natural_language_examples=["查看权限说明", "权限说明", "安全边界", "查看安全边界"],
    ),
    _skill(
        "bot.status",
        "Show current system status: Gateway, LLM Proxy, DB, ComfyUI mode, skill count.",
        True,
        bot_skills.bot_status,
        {},
        domain="bot",
        risk_level="readonly",
        natural_language_examples=["查看当前系统状态", "系统状态", "bot status"],
    ),
    _skill(
        "bot.errors",
        "Show the last 10 error records from the audit log.",
        True,
        bot_skills.bot_errors,
        {},
        domain="bot",
        risk_level="readonly",
        natural_language_examples=["查看最近错误", "最近错误", "recent errors"],
    ),
    _skill(
        "agent.current_work",
        "Summarize active production context across ComfyUI, Cherry, frame extraction, pipeline, pending confirmations, recent errors and GPU.",
        True,
        agent_ops_skills.current_work,
        {
            "root": "string optional",
            "include_gpu": "boolean optional",
            "date_start": "string optional YYYY-MM-DD",
            "date_end": "string optional YYYY-MM-DD",
            "query": "string optional file name or task id",
            "detail": "boolean optional",
            "media_type": "string optional video/image",
            "include_finished": "boolean optional",
        },
        domain="agent",
        risk_level="readonly",
        natural_language_examples=[
            "现在机器在跑什么",
            "当前所有任务情况",
            "现在这个自动化流程到哪里了",
        ],
    ),
    _skill(
        "agent.diagnose",
        "Diagnose likely production blockers and propose next safe skill calls without starting destructive work.",
        True,
        agent_ops_skills.diagnose,
        {"root": "string optional", "include_gpu": "boolean optional"},
        domain="agent",
        risk_level="readonly",
        natural_language_examples=[
            "为什么这个任务没开始",
            "帮我诊断一下现在卡在哪里",
            "你看看现在什么情况",
            "agent 自己判断下一步应该做什么",
        ],
    ),
    _skill(
        "sticker.info",
        "Show emotional sticker reply settings and available local PNG/GIF sticker count.",
        True,
        sticker_skills.info,
        {},
        domain="sticker",
        risk_level="readonly",
        natural_language_examples=["表情包状态", "情绪回复配置", "看看表情包池"],
    ),
    _skill(
        "sticker.send_random",
        "Send one random local emotional sticker to the current Feishu chat.",
        True,
        sticker_skills.send_random,
        {},
        domain="sticker",
        risk_level="egress_caution",
        natural_language_examples=["随机发个表情包", "来个表情包", "发个 sticker"],
    ),
    _skill(
        "emotion.respond",
        "Respond to a user's emotional message with a short warm reply, without touching production tools.",
        True,
        emotion_skills.respond,
        {"text": "string"},
        domain="emotion",
        risk_level="readonly",
        natural_language_examples=["你是笨蛋吗", "我真的服了", "烦死了"],
    ),
    _skill(
        "life.location",
        "Return the user's remembered or configured default location for daily-life chat.",
        True,
        life_skills.location,
        {},
        domain="life",
        risk_level="readonly",
        natural_language_examples=["我在哪里", "你知道我在哪吗", "当前位置"],
    ),
    _skill(
        "life.set_location",
        "Remember the user's city or area for this conversation so weather and food suggestions can use it.",
        True,
        life_skills.set_location,
        {"location": "string"},
        domain="life",
        risk_level="write_safe",
        natural_language_examples=["我在上海", "记住我现在在徐汇", "我人在北京"],
    ),
    _skill(
        "life.weather",
        "Fetch current weather for a city or remembered/default location, with a short practical suggestion.",
        True,
        life_skills.weather,
        {"location": "string optional", "timeout_seconds": "integer optional"},
        domain="life",
        risk_level="network_read",
        natural_language_examples=["今天天气怎么样", "上海会下雨吗", "出门要带伞吗", "热不热"],
    ),
    _skill(
        "life.food_suggest",
        "Suggest low-decision meal or takeout options based on meal time, mood, weather and location.",
        True,
        life_skills.food_suggest,
        {"meal": "string optional", "location": "string optional", "mood": "string optional", "weather_text": "string optional"},
        domain="life",
        risk_level="readonly",
        natural_language_examples=["中午吃什么", "午饭点什么外卖", "晚饭吃啥", "今天吃点什么比较好"],
    ),
    _skill(
        "web.fetch_url",
        "Fetch an explicit HTTP/HTTPS URL and return title plus cleaned text excerpt. Read-only network access.",
        True,
        web_skills.fetch_url,
        {"url": "string", "max_chars": "integer optional", "timeout_seconds": "integer optional"},
        domain="web",
        risk_level="network_read",
        natural_language_examples=["读取这个网页 https://example.com", "帮我看一下这个 URL 的内容"],
    ),
    _skill(
        "web.search",
        "Search the public web and return candidate pages with title, URL, domain and snippets. Read-only network access.",
        True,
        web_skills.search_web,
        {"query": "string", "max_results": "integer optional", "timeout_seconds": "integer optional"},
        domain="web",
        risk_level="network_read",
        natural_language_examples=["搜索陶喆 蝴蝶 歌词", "网上查一下 ComfyUI 最新版本", "帮我搜这个问题"],
    ),
    _skill(
        "web.research",
        "Search the public web, fetch top pages, and return a concise source-grounded synthesis.",
        True,
        web_skills.research,
        {"query": "string", "max_results": "integer optional", "max_pages": "integer optional", "max_chars_per_page": "integer optional", "timeout_seconds": "integer optional"},
        domain="web",
        risk_level="network_read",
        natural_language_examples=["搜索并整合这个问题", "帮我调研一下", "搜几篇资料总结给我"],
    ),
    _skill(
        "p4.help",
        "Show available P4 assistant capabilities and safety rules.",
        True,
        p4_skills.help,
        {},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["p4 现在功能有哪些", "P4 助手会做什么", "p4 help"],
    ),
    _skill(
        "p4.check",
        "Run Shelve-only P4 safety checks for the configured Unity UI asset workspace.",
        True,
        p4_skills.check,
        parameters={
            "workflow": {"type": "string", "required": False},
            "workspace": {"type": "string", "required": False},
            "allow_delete": {"type": "boolean", "required": False},
        },
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["p4 安全检查", "检查 P4 UI 导入 workspace"],
    ),
    _skill(
        "p4.list_cls",
        "List pending and shelved changelists for the configured P4 workspace.",
        True,
        p4_skills.list_cls,
        parameters={
            "workflow": {"type": "string", "required": False},
            "workspace": {"type": "string", "required": False},
        },
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["现在工作区有哪些 CL", "列一下 p4 changelist", "查看当前 workspace 的 shelved CL"],
    ),
    _skill(
        "p4.cleanup_cl",
        "Delete shelf, revert opened files, and delete a pending changelist. Submit is disabled.",
        True,
        p4_skills.cleanup_cl,
        parameters={
            "workflow": {"type": "string", "required": False},
            "workspace": {"type": "string", "required": False},
            "cl": {"type": "string", "required": True},
            "allow_delete": {"type": "boolean", "required": False},
        },
        domain="p4",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["删除 CL 6901", "清理 p4 changelist 6901", "取消这次 shelf 6901"],
    ),
    _skill(
        "p4.preview",
        "Preview reconcile for managed Unity UI emoji asset paths only.",
        True,
        p4_skills.preview,
        parameters={
            "workflow": {"type": "string", "required": False},
            "workspace": {"type": "string", "required": False},
            "allow_delete": {"type": "boolean", "required": False},
        },
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["预览 UI 表情资源 P4 改动", "p4 preview"],
    ),
    _skill(
        "p4.create_cl",
        "Create a pending changelist with Shelve-only metadata.",
        True,
        p4_skills.create_cl,
        parameters={
            "workflow": {"type": "string", "required": False},
            "workspace": {"type": "string", "required": False},
            "desc": {"type": "string", "required": True},
        },
        domain="p4",
        risk_level="medium",
        requires_confirmation=True,
        natural_language_examples=["创建 UI 表情导入 changelist"],
    ),
    _skill(
        "p4.shelve",
        "Shelve a checked changelist without submitting.",
        True,
        p4_skills.shelve,
        parameters={
            "workflow": {"type": "string", "required": False},
            "workspace": {"type": "string", "required": False},
            "cl": {"type": "string", "required": True},
            "force": {"type": "boolean", "required": False},
            "allow_delete": {"type": "boolean", "required": False},
        },
        domain="p4",
        risk_level="medium",
        requires_confirmation=True,
        natural_language_examples=["shelve changelist 123456", "搁置 CL 123456"],
    ),
    _skill(
        "p4.report",
        "Generate a Feishu-ready Shelve-only P4 report.",
        True,
        p4_skills.report,
        parameters={
            "workflow": {"type": "string", "required": False},
            "workspace": {"type": "string", "required": False},
            "cl": {"type": "string", "required": True},
            "allow_delete": {"type": "boolean", "required": False},
        },
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["生成 P4 shelf 飞书报告"],
    ),
    _skill(
        "p4.shelve_ui_import",
        "Run check, preview, create changelist, reconcile, shelve, and report for Unity UI import results.",
        True,
        p4_skills.shelve_ui_import,
        parameters={
            "workflow": {"type": "string", "required": False},
            "workspace": {"type": "string", "required": False},
            "desc": {"type": "string", "required": True},
            "yes": {"type": "boolean", "required": False},
            "force": {"type": "boolean", "required": False},
            "allow_delete": {"type": "boolean", "required": False},
        },
        domain="p4",
        risk_level="medium",
        requires_confirmation=True,
        natural_language_examples=["一键 shelve UI 表情导入结果"],
    ),
    _skill(
        "p4.inspect",
        "Run p4 info and compare it with configured workspace settings.",
        True,
        p4_skills.inspect,
        {"workflow": "string optional", "workspace": "string optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["检查 p4 workspace", "p4 info", "看看 ai_art_comfyui p4 配置"],
    ),
    _skill(
        "p4.inventory",
        "Show read-only P4 topology: p4 info, depots, clients for configured user, current client spec, streams and configured mappings.",
        True,
        p4_skills.inventory,
        {"workflow": "string optional", "workspace": "string optional", "max_clients": "integer optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["p4 有多少 depot 和 workspace", "看看 p4 depot workspace 对应关系", "p4 拓扑信息", "p4 总览"],
    ),
    _skill(
        "p4.workspace_details",
        "Show detailed read-only client specs for the configured user's P4 workspaces: root, stream, view, update/access, options.",
        True,
        p4_skills.workspace_details,
        {"workflow": "string optional", "workspace": "string optional", "max_clients": "integer optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["这个 depot 对应的三个工作区详情", "p4 workspace 详情", "show p4 workspace details"],
    ),
    _skill(
        "p4.compare_depot",
        "Compare local P4 workspace state with depot/head: haveRev vs headRev, sync preview, reconcile preview and opened diff.",
        True,
        p4_skills.compare_depot,
        {"workflow": "string optional", "workspace": "string optional", "paths": "array optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["对比本地工作区和服务器 depot 文件差异", "看看本地和 depot 有什么差异", "compare local p4 workspace with depot"],
    ),
    _skill(
        "p4.list_workflows",
        "List workflow JSON files currently synced in the configured P4 workspace.",
        True,
        p4_skills.list_workflows,
        {"workflow": "string optional", "workspace": "string optional", "max_results": "integer optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["我们现在有哪些工作流呢 p4", "列一下 p4 workflows", "看看 P4 拉下来的工作流"],
    ),
    _skill(
        "p4.preview_setup_workspace",
        "Preview the P4 client spec for configured workspace setup. Does not write anything.",
        True,
        p4_skills.preview_setup_workspace,
        {"workflow": "string optional", "workspace": "string optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["预览创建 p4 workspace", "看看 workspace client spec", "预览初始化 p4 工作区"],
    ),
    _skill(
        "p4.setup_workspace",
        "Create/update the P4 client spec and workspace root after explicit confirmation.",
        True,
        p4_skills.setup_workspace,
        {"workflow": "string optional", "workspace": "string optional", "confirmation": "boolean"},
        domain="p4",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["确认创建 p4 workspace", "初始化 p4 工作区", "创建 Perforce client"],
    ),
    _skill(
        "p4.status",
        "Show P4 opened files, reconcile preview and diff summary.",
        True,
        p4_skills.status,
        {"workflow": "string optional", "workspace": "string optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["看看 ai_art_comfyui 现在改了什么", "p4 查看状态", "看看 P4 改动"],
    ),
    _skill(
        "p4.workspace_info",
        "Show read-only P4 workspace root, stream, managed paths and forbidden paths.",
        True,
        p4_skills.workspace_info,
        {"workflow": "string optional", "workspace": "string optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["查看 p4 workspace 信息", "当前 p4 分支是什么", "workspace-info"],
    ),
    _skill(
        "p4.streams",
        "List visible P4 streams without changing server state.",
        True,
        p4_skills.streams,
        {"workflow": "string optional", "workspace": "string optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["查看 p4 streams", "有哪些分支", "streams"],
    ),
    _skill(
        "p4.switch_stream",
        "Preview or confirm switching the configured workspace stream. Preview is default; real switch requires confirmation.",
        True,
        p4_skills.switch_stream,
        {"workflow": "string optional", "workspace": "string optional", "stream": "string", "preview": "boolean optional", "yes": "boolean optional", "allow_opened": "boolean optional"},
        domain="p4",
        risk_level="write_caution",
        requires_confirmation=True,
        natural_language_examples=["预览切换 p4 分支到 001", "switch stream preview"],
    ),
    _skill(
        "p4.get_latest",
        "Run p4 sync for managed paths by default, or preview/all scope with explicit confirmation.",
        True,
        p4_skills.get_latest,
        {"workflow": "string optional", "workspace": "string optional", "scope": "string optional", "preview": "boolean optional", "yes": "boolean optional"},
        domain="p4",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["p4 get latest managed", "预览同步 p4"],
    ),
    _skill(
        "p4.preview_sync",
        "Preview p4 sync with sync -n. Does not change files.",
        True,
        p4_skills.preview_sync,
        {"workflow": "string optional", "workspace": "string optional", "paths": "array optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["预览 workflows 拉最新", "p4 sync -n", "预览同步"],
    ),
    _skill(
        "p4.sync",
        "Run real p4 sync after explicit confirmation.",
        True,
        p4_skills.sync,
        {"workflow": "string optional", "workspace": "string optional", "paths": "array optional", "confirmation": "boolean"},
        domain="p4",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["确认拉最新", "执行 p4 sync"],
    ),
    _skill(
        "p4.preview_reconcile",
        "Preview p4 reconcile with reconcile -n. Does not open files.",
        True,
        p4_skills.preview_reconcile,
        {"workflow": "string optional", "workspace": "string optional", "paths": "array optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["帮我预览 reconcile", "p4 reconcile -n", "看看哪些文件要 add/edit/delete"],
    ),
    _skill(
        "p4.reconcile",
        "Run real p4 reconcile after explicit confirmation.",
        True,
        p4_skills.reconcile,
        {"workflow": "string optional", "workspace": "string optional", "paths": "array optional", "confirmation": "boolean"},
        domain="p4",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["我确认，执行 reconcile", "确认 p4 reconcile"],
    ),
    _skill(
        "p4.build_changelist",
        "Build a changelist summary from opened files, reconcile preview and diff.",
        True,
        p4_skills.build_changelist,
        {"workflow": "string optional", "workspace": "string optional"},
        domain="p4",
        risk_level="readonly",
        natural_language_examples=["帮我生成 changelist 描述", "总结这次 P4 改动"],
    ),
    _skill(
        "p4.create_changelist",
        "Create a pending changelist after confirmation.",
        True,
        p4_skills.create_changelist,
        {"workflow": "string optional", "workspace": "string optional", "description": "string", "files": "array optional", "confirmation": "boolean"},
        domain="p4",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["创建 pending changelist"],
    ),
    _skill(
        "p4.submit",
        "Submit a changelist after second confirmation and status checks.",
        True,
        p4_skills.submit,
        {"workflow": "string optional", "workspace": "string optional", "changelist": "string", "confirmation": "boolean"},
        domain="p4",
        risk_level="high",
        requires_confirmation=True,
        natural_language_examples=["我确认，提交 changelist 123456"],
    ),
    # ---- file skills -------------------------------------------------------
    _skill(
        "file.list_allowed",
        "List files and directories under an allowed path. Metadata only.",
        True,
        file_skills.file_list_allowed,
        {"path": "string", "max_items": "integer optional"},
        domain="file",
        risk_level="readonly",
        examples=[{"skill": "file.list_allowed", "arguments": {"path": "E:\\", "max_items": 20}}],
        natural_language_examples=["看看 E 盘有哪些文件", "列出 E:\\assetclaw-matting-bot 下的文件"],
    ),
    _skill(
        "file.copy",
        "Copy one file under allowed roots to another allowed path.",
        True,
        file_skills.file_copy,
        {"src_path": "string", "dst_path": "string", "overwrite": "boolean"},
        domain="file",
        risk_level="write_safe",
        examples=[{
            "skill": "file.copy",
            "arguments": {
                "src_path": "E:\\assetclaw-matting-bot\\README.md",
                "dst_path": "E:\\assetclaw-matting-bot\\storage\\README_copy.md",
                "overwrite": False,
            },
        }],
        natural_language_examples=[
            "把 E:\\assetclaw-matting-bot\\README.md 复制到 E:\\assetclaw-matting-bot\\storage\\README_copy.md",
        ],
    ),
    _skill(
        "file.move",
        "Move or rename one file or directory under allowed roots.",
        True,
        file_skills.file_move,
        {"src_path": "string", "dst_path": "string", "overwrite": "boolean"},
        domain="file",
        risk_level="write_caution",
        requires_confirmation=True,
        examples=[{
            "skill": "file.move",
            "arguments": {
                "src_path": "E:\\assetclaw-matting-bot\\storage\\README_copy.md",
                "dst_path": "E:\\assetclaw-matting-bot\\storage\\README_moved.md",
                "overwrite": False,
            },
        }],
        natural_language_examples=[
            "把 E:\\assetclaw-matting-bot\\storage\\README_copy.md 移动到 E:\\assetclaw-matting-bot\\storage\\README_moved.md",
        ],
    ),
    _skill(
        "file.mkdir",
        "Create a directory under allowed roots.",
        True,
        file_skills.file_mkdir,
        {"path": "string", "parents": "boolean", "exist_ok": "boolean"},
        domain="file",
        risk_level="write_safe",
        examples=[{"skill": "file.mkdir", "arguments": {"path": "E:\\assetclaw-matting-bot\\storage\\new_folder"}}],
        natural_language_examples=["创建目录 E:\\assetclaw-matting-bot\\storage\\feishu_test"],
    ),
    _skill(
        "file.exists",
        "Check whether a file or directory exists under allowed roots.",
        True,
        file_skills.file_exists,
        {"path": "string"},
        domain="file",
        risk_level="readonly",
        examples=[{"skill": "file.exists", "arguments": {"path": "E:\\assetclaw-matting-bot\\README.md"}}],
        natural_language_examples=["E:\\assetclaw-matting-bot\\README.md 是否存在"],
    ),
    _skill(
        "file.info",
        "Get metadata (size, mtime, type) of a file or directory. Does not read content.",
        True,
        file_extra_skills.file_info,
        {"path": "string"},
        domain="file",
        risk_level="readonly",
        examples=[{"skill": "file.info", "arguments": {"path": "E:\\assetclaw-matting-bot\\README.md"}}],
        natural_language_examples=["查看 E:\\assetclaw-matting-bot\\README.md 的信息"],
    ),
    _skill(
        "file.find_name",
        "Search for files or directories by name pattern within allowed roots.",
        True,
        file_extra_skills.file_find_name,
        {"name_pattern": "string", "search_root": "string optional", "max_results": "integer optional", "max_depth": "integer optional"},
        domain="file",
        risk_level="readonly",
        examples=[{"skill": "file.find_name", "arguments": {"name_pattern": ".ps1", "max_results": 20}}],
        natural_language_examples=["搜索文件名包含 batch 的文件"],
    ),
    _skill(
        "file.tree",
        "List a directory tree with depth and item limits. No file content.",
        True,
        file_extra_skills.file_tree,
        {"path": "string", "max_depth": "integer optional", "max_items": "integer optional"},
        domain="file",
        risk_level="readonly",
        examples=[{"skill": "file.tree", "arguments": {"path": "E:\\assetclaw-matting-bot\\scripts", "max_depth": 2}}],
        natural_language_examples=["显示 E:\\assetclaw-matting-bot 目录树"],
    ),
    _skill(
        "file.recent",
        "List recently modified files within allowed roots.",
        True,
        file_extra_skills.file_recent,
        {"hours": "integer optional", "search_root": "string optional", "max_results": "integer optional"},
        domain="file",
        risk_level="readonly",
        examples=[{"skill": "file.recent", "arguments": {"hours": 24, "max_results": 20}}],
        natural_language_examples=["查看最近 24 小时内修改的文件"],
    ),
    _skill(
        "file.list_by_type",
        "List files by extension/category such as image, video, table, archive.",
        True,
        media_skills.file_list_by_type,
        {"path": "string", "kind": "string optional", "extensions": "list optional", "recursive": "boolean optional", "max_results": "integer optional"},
        domain="file",
        risk_level="readonly",
        natural_language_examples=["列出 E:\\ 下面的图片文件", "找出 E:\\assetclaw-matting-bot 里的表格文件"],
    ),
    _skill(
        "file.copy_as",
        "Copy a file to a chosen directory with a new file name.",
        True,
        media_skills.file_copy_as,
        {"src_path": "string", "new_name": "string", "dst_dir": "string optional", "overwrite": "boolean optional"},
        domain="file",
        risk_level="write_safe",
        natural_language_examples=["把 E:\\a.png 复制一份到原目录并改名为 a_backup.png"],
    ),
    _skill(
        "file.duplicate_same_dir",
        "Duplicate a file in the same directory using a suffix.",
        True,
        media_skills.file_duplicate_same_dir,
        {"src_path": "string", "suffix": "string optional", "overwrite": "boolean optional"},
        domain="file",
        risk_level="write_safe",
        natural_language_examples=["把 E:\\a.png 在原路径复制一份，后缀加 _bak"],
    ),
    _skill(
        "file.zip_paths",
        "Create a zip archive from selected files/directories under allowed roots.",
        True,
        media_skills.file_zip_paths,
        {"paths": "list[string]", "zip_path": "string", "overwrite": "boolean optional"},
        domain="file",
        risk_level="write_caution",
        natural_language_examples=["把 E:\\assetclaw-matting-bot\\storage\\batch_outputs 打包成 zip"],
    ),
    _skill(
        "feishu.zip_and_send",
        "Create a zip archive from allowed files/directories, then send the zip to the current Feishu chat in one atomic skill.",
        True,
        media_skills.feishu_zip_and_send,
        {"paths": "list[string]", "zip_path": "string", "overwrite": "boolean optional", "file_name": "string optional"},
        domain="feishu",
        risk_level="egress_caution",
        natural_language_examples=["把共享盘 input 文件夹压缩成 zip 并发送给我"],
    ),
    _skill(
        "workspace.roots",
        "Show allowed workspace roots. C drive is intentionally excluded.",
        True,
        workspace_skills.workspace_roots,
        {},
        domain="workspace",
        risk_level="readonly",
        natural_language_examples=["查看允许访问的磁盘", "哪些盘可以操作"],
    ),
    _skill(
        "workspace.disk_usage",
        "Show free/used/total space for allowed workspace roots.",
        True,
        workspace_skills.workspace_disk_usage,
        {},
        domain="workspace",
        risk_level="readonly",
        natural_language_examples=["查看 D E F 盘空间", "磁盘空间状态"],
    ),
    _skill(
        "file.read_text",
        "Read a small text file from allowed roots. Denied paths and binary extensions are blocked.",
        True,
        workspace_skills.file_read_text,
        {"path": "string", "max_chars": "integer optional", "encoding": "string optional"},
        domain="file",
        risk_level="readonly",
        natural_language_examples=["读取 D:\\project\\README.md 前 2000 个字符"],
    ),
    _skill(
        "file.write_text",
        "Create or overwrite a text file under allowed roots.",
        True,
        workspace_skills.file_write_text,
        {"path": "string", "content": "string", "overwrite": "boolean optional", "encoding": "string optional"},
        domain="file",
        risk_level="write_safe",
        natural_language_examples=["在 F:\\notes\\todo.md 写入一段文本"],
    ),
    _skill(
        "file.append_text",
        "Append text to an allowed text file.",
        True,
        workspace_skills.file_append_text,
        {"path": "string", "content": "string", "encoding": "string optional", "create": "boolean optional"},
        domain="file",
        risk_level="write_safe",
        natural_language_examples=["往 E:\\log.txt 追加一行"],
    ),
    _skill(
        "file.hash",
        "Calculate a file hash for integrity checks.",
        True,
        workspace_skills.file_hash,
        {"path": "string", "algorithm": "sha256 or md5 optional"},
        domain="file",
        risk_level="readonly",
        natural_language_examples=["计算 D:\\asset.zip 的 sha256"],
    ),
    _skill(
        "file.batch_info",
        "Get metadata for a batch of paths.",
        True,
        workspace_skills.file_batch_info,
        {"paths": "list[string]"},
        domain="file",
        risk_level="readonly",
        natural_language_examples=["批量检查这些文件是否存在"],
    ),
    _skill(
        "file.copy_tree",
        "Copy a directory tree across allowed roots with file-count limit.",
        True,
        workspace_skills.file_copy_tree,
        {"src_path": "string", "dst_path": "string", "overwrite": "boolean optional", "max_files": "integer optional"},
        domain="file",
        risk_level="write_safe",
        natural_language_examples=["把 D:\\assets 复制到 F:\\backup\\assets"],
    ),
    _skill(
        "file.copy_many",
        "Copy many files in one call.",
        True,
        workspace_skills.file_copy_many,
        {"items": "list[{src_path:string,dst_path:string}]", "overwrite": "boolean optional"},
        domain="file",
        risk_level="write_safe",
        natural_language_examples=["把这几个文件分别复制到 F:\\backup"],
    ),
    _skill(
        "file.move_many",
        "Move many files in one call. Requires confirmation.",
        True,
        workspace_skills.file_move_many,
        {"items": "list[{src_path:string,dst_path:string}]", "overwrite": "boolean optional"},
        domain="file",
        risk_level="write_caution",
        requires_confirmation=True,
        natural_language_examples=["把这几个文件批量移动到 F:\\archive"],
    ),
    _skill(
        "file.mkdir_many",
        "Create many directories in one call.",
        True,
        workspace_skills.file_mkdir_many,
        {"paths": "list[string]", "parents": "boolean optional", "exist_ok": "boolean optional"},
        domain="file",
        risk_level="write_safe",
        natural_language_examples=["创建 project 的 input output temp 三个目录"],
    ),
    _skill(
        "file.rename_many",
        "Rename files using explicit source/destination pairs. Requires confirmation.",
        True,
        workspace_skills.file_rename_many,
        {"items": "list[{src_path:string,dst_path:string}]", "overwrite": "boolean optional"},
        domain="file",
        risk_level="write_caution",
        requires_confirmation=True,
        natural_language_examples=["把这些文件分别改成指定的新名字"],
    ),
    _skill(
        "file.rename_sequence",
        "Rename selected files in order to 1, 2, 3... while preserving extensions. Requires confirmation.",
        True,
        workspace_skills.file_rename_sequence,
        {"paths": "list[string]", "start": "integer optional", "padding": "integer optional", "preserve_extension": "boolean optional", "overwrite": "boolean optional"},
        domain="file",
        risk_level="write_caution",
        requires_confirmation=True,
        natural_language_examples=["把刚才列出的图片按顺序改名为 1 2 3 4 5"],
    ),
    _skill(
        "file.unzip",
        "Extract a zip archive into an allowed directory.",
        True,
        workspace_skills.file_unzip,
        {"zip_path": "string", "dst_dir": "string", "overwrite": "boolean optional", "max_files": "integer optional"},
        domain="file",
        risk_level="write_caution",
        requires_confirmation=True,
        natural_language_examples=["把 F:\\assets.zip 解压到 F:\\assets"],
    ),
    _skill(
        "file.search_text",
        "Search text inside allowed text files under a directory.",
        True,
        utility_skills.file_search_text,
        {"path": "string", "query": "string", "extensions": "list optional", "max_results": "integer optional", "max_depth": "integer optional"},
        domain="file",
        risk_level="readonly",
        natural_language_examples=["在 E:\\project 里搜索 TODO", "搜索 README 里包含 ComfyUI 的地方"],
    ),
    _skill(
        "file.preview",
        "Preview text or binary header of a file.",
        True,
        utility_skills.file_preview,
        {"path": "string", "max_chars": "integer optional", "tail": "boolean optional"},
        domain="file",
        risk_level="readonly",
        natural_language_examples=["预览 E:\\a.txt", "看一下这个日志最后几行"],
    ),
    _skill(
        "file.count",
        "Count files by category under a directory.",
        True,
        utility_skills.file_count,
        {"path": "string", "recursive": "boolean optional", "max_depth": "integer optional"},
        domain="file",
        risk_level="readonly",
        natural_language_examples=["统计 E:\\input 里有多少图片", "数一下这个目录里的文件类型"],
    ),
    _skill(
        "file.manifest",
        "Export a JSON or CSV manifest for files under an allowed directory.",
        True,
        utility_skills.file_manifest,
        {"path": "string", "output_path": "string", "recursive": "boolean optional", "max_items": "integer optional", "format": "json or csv optional"},
        domain="file",
        risk_level="write_safe",
        natural_language_examples=["把 E:\\input 的文件清单导出成 E:\\input_manifest.csv"],
    ),
    _skill(
        "archive.list",
        "List files inside a zip archive without extracting it.",
        True,
        utility_skills.archive_list,
        {"path": "string", "max_items": "integer optional"},
        domain="archive",
        risk_level="readonly",
        natural_language_examples=["看看这个 zip 里面有哪些文件"],
    ),
    _skill(
        "json.query",
        "Read a JSON file and optionally select a JSON Pointer path.",
        True,
        utility_skills.json_query,
        {"path": "string", "pointer": "string optional"},
        domain="file",
        risk_level="readonly",
        natural_language_examples=["读取 workflow json 的 /nodes/0", "查看这个 JSON 的内容"],
    ),
    _skill(
        "csv.summary",
        "Show columns and sample rows for a CSV/TSV file.",
        True,
        utility_skills.csv_summary,
        {"path": "string", "max_rows": "integer optional"},
        domain="file",
        risk_level="readonly",
        natural_language_examples=["查看这个 CSV 表格有哪些列", "预览这个表格前几行"],
    ),
    _skill(
        "file.delete",
        "Delete one allowed file or directory. Requires confirmation.",
        True,
        workspace_skills.file_delete,
        {"path": "string", "recursive": "boolean optional"},
        domain="file",
        risk_level="danger_confirm",
        requires_confirmation=True,
        natural_language_examples=["删除 F:\\temp\\old.png"],
    ),
    _skill(
        "file.empty_dir",
        "Empty an allowed directory. Requires confirmation.",
        True,
        workspace_skills.file_empty_dir,
        {"path": "string"},
        domain="file",
        risk_level="danger_confirm",
        requires_confirmation=True,
        natural_language_examples=["清空 F:\\temp"],
    ),
    # ---- image/media skills ------------------------------------------------
    _skill(
        "image.list",
        "List image files under an allowed directory.",
        True,
        media_skills.image_list,
        {"path": "string", "recursive": "boolean optional", "max_results": "integer optional", "max_depth": "integer optional"},
        domain="image",
        risk_level="readonly",
        natural_language_examples=["列出 E 盘的图片文件", "递归查看 E:\\assetclaw-matting-bot 里的图片"],
    ),
    _skill(
        "image.info",
        "Read image metadata: width, height, format, mode, file size. Does not modify content.",
        True,
        media_skills.image_info,
        {"path": "string"},
        domain="image",
        risk_level="readonly",
        natural_language_examples=["查看 E:\\a.png 的图片尺寸"],
    ),
    _skill(
        "image.batch_info",
        "Read metadata for many images.",
        True,
        media_skills.image_batch_info,
        {"paths": "list[string]"},
        domain="image",
        risk_level="readonly",
        natural_language_examples=["批量查看这些图片的尺寸"],
    ),
    _skill(
        "image.convert_format",
        "Convert one image to another format/path.",
        True,
        media_skills.image_convert_format,
        {"src_path": "string", "dst_path": "string", "format": "string optional", "overwrite": "boolean optional"},
        domain="image",
        risk_level="write_safe",
        natural_language_examples=["把 E:\\a.png 转成 E:\\a.jpg"],
    ),
    _skill(
        "image.resize",
        "Resize one image to exact width and height.",
        True,
        media_skills.image_resize,
        {"src_path": "string", "dst_path": "string", "width": "integer", "height": "integer", "overwrite": "boolean optional"},
        domain="image",
        risk_level="write_safe",
        natural_language_examples=["把 E:\\a.png 缩放成 1024x1024"],
    ),
    # ---- feishu delivery skills -------------------------------------------
    _skill(
        "feishu.send_file",
        "Upload an allowed local file and send it to the current Feishu chat.",
        True,
        media_skills.feishu_send_file,
        {"path": "string", "file_name": "string optional"},
        domain="feishu",
        risk_level="egress_caution",
        natural_language_examples=["把 E:\\assetclaw-matting-bot\\README.md 通过飞书发给我"],
    ),
    _skill(
        "feishu.send_file_by_name",
        "Find one allowed local file by name or shortened name, then send it to the current Feishu chat.",
        True,
        media_skills.feishu_send_file_by_name,
        {"name_pattern": "string", "search_root": "string optional", "file_name": "string optional", "max_depth": "integer optional"},
        domain="feishu",
        risk_level="egress_caution",
        natural_language_examples=["把 E 盘里 img_v3_02125_53d2b164...608g.png 这个文件发给我"],
    ),
    _skill(
        "feishu.send_image",
        "Upload an allowed local image and send it as an inline Feishu image preview.",
        True,
        media_skills.feishu_send_image,
        {"path": "string"},
        domain="feishu",
        risk_level="egress_caution",
        natural_language_examples=["把 E:\\1.png 用图片形式发给我", "预览一下刚刚那张图"],
    ),
    _skill(
        "feishu.send_image_by_name",
        "Find one allowed local image by name or shortened name, then send it as an inline Feishu image preview.",
        True,
        media_skills.feishu_send_image_by_name,
        {"name_pattern": "string", "search_root": "string optional", "max_depth": "integer optional"},
        domain="feishu",
        risk_level="egress_caution",
        natural_language_examples=["把 E 盘里 1.png 用图片形式发给我"],
    ),
    # ---- translation skills -------------------------------------------------
    _skill(
        "text.process",
        "Run a pure text task with DeepSeek: polish, rewrite, summarize, organize, extract action items, or format text.",
        True,
        text_skills.process_text,
        {
            "text": {"type": "string"},
            "instruction": {"type": "string"},
            "style": {"type": "string", "default": "natural"},
        },
        domain="text",
        risk_level="readonly",
        natural_language_examples=["润色这段话", "把这段话整理成飞书文档格式", "总结下面这段内容", "改写得自然一点"],
    ),
    _skill(
        "translate.text",
        "Translate user-provided text using DeepSeek first, with LLM Proxy fallback. Returns natural language only.",
        True,
        translation_skills.translate_text,
        {"text": "string", "target_language": "string", "source_language": "string optional", "style": "string optional"},
        domain="translate",
        risk_level="readonly",
        natural_language_examples=["把这句话翻译成英文：你好，今天辛苦了", "翻译成日语：这个文件已经处理好了"],
    ),
    _skill(
        "translate.image_text",
        "Extract visible text from an image and translate it into the target language using a multimodal LLM.",
        True,
        translation_skills.translate_image_text,
        {"image_path": "string", "target_language": "string", "source_language": "string optional", "instruction": "string optional"},
        domain="translate",
        risk_level="readonly",
        natural_language_examples=["把刚刚这张图里的文字翻译成中文", "识别这张图片里的英文并翻译成日语"],
    ),
    _skill(
        "image.ocr",
        "Extract visible text from a supported image using a multimodal LLM.",
        True,
        translation_skills.image_ocr,
        {"image_path": "string", "instruction": "string optional"},
        domain="image",
        risk_level="readonly",
        natural_language_examples=["提取刚刚那张图里的文字", "识别图片中的文字"],
    ),
    _skill(
        "image.describe",
        "Describe a supported image using a multimodal LLM, with a clear fallback when vision is not configured.",
        True,
        translation_skills.image_describe,
        {"image_path": "string", "instruction": "string optional"},
        domain="image",
        risk_level="readonly",
        natural_language_examples=["分析这张图片内容", "描述一下刚刚那张图", "图里有什么"],
    ),
    _skill(
        "speech.transcribe",
        "Transcribe a downloaded Feishu voice/audio attachment or local audio file into text for the Brain Router.",
        True,
        speech_skills.transcribe,
        {"audio_path": "string", "language": "string optional", "prompt": "string optional"},
        domain="speech",
        risk_level="readonly",
        natural_language_examples=["把这条语音转成文字", "识别这段音频里的话", "语音输入"],
    ),
    _skill(
        "speech.synthesize",
        "Synthesize text into a local audio file using the configured TTS backend.",
        True,
        speech_skills.synthesize,
        {"text": "string", "output_path": "string optional", "voice": "string optional", "engine": "string optional", "rate": "string optional"},
        domain="speech",
        risk_level="write_safe",
        natural_language_examples=["把这段话合成为语音", "生成一段初音语音回复"],
    ),
    _skill(
        "speech.send_tts",
        "Synthesize text into speech and send the audio file to the current Feishu chat.",
        True,
        speech_skills.send_tts,
        {"text": "string", "voice": "string optional", "engine": "string optional", "rate": "string optional"},
        domain="speech",
        risk_level="egress_caution",
        natural_language_examples=["用语音回复我", "把这段话用 TTS 发给我"],
    ),
    # ---- memory skills -----------------------------------------------------
    _skill(
        "memory.remember",
        "Store a user-approved memory note in local SQLite.",
        True,
        memory_skills.memory_remember,
        {"key": "string", "value": "string", "scope": "string optional", "source": "string optional"},
        domain="memory",
        risk_level="write_safe",
        natural_language_examples=["记住：项目名称是 AssetClaw"],
    ),
    _skill(
        "memory.list",
        "List local SQLite memory notes.",
        True,
        memory_skills.memory_list,
        {"scope": "string optional", "limit": "integer optional"},
        domain="memory",
        risk_level="readonly",
        natural_language_examples=["查看记忆列表"],
    ),
    _skill(
        "memory.context_pack",
        "Build a backend RAG-style context pack: long-term summary plus reverse-recent conversation turns, optionally compacting old messages first.",
        True,
        memory_skills.memory_context_pack,
        {
            "conversation_id": "string optional",
            "recent_limit": "integer optional",
            "max_chars": "integer optional",
            "force_compact": "boolean optional",
            "keep_messages": "integer optional",
        },
        domain="memory",
        risk_level="readonly",
        natural_language_examples=["生成这个会话的 RAG 上下文包", "把最近对话逆序压缩一下", "查看 test 会话上下文包"],
    ),
    _skill(
        "memory.compact",
        "Manually compact older brain messages into a conversation summary while keeping the newest messages raw.",
        True,
        memory_skills.memory_compact,
        {"conversation_id": "string optional", "keep_messages": "integer optional", "max_chars": "integer optional"},
        domain="memory",
        risk_level="write_safe",
        natural_language_examples=["压缩 test 会话记忆，只保留最近 12 条", "手动整理这个会话的长期记忆"],
    ),
    # ---- matting skills ----------------------------------------------------
    _skill(
        "matting.batch_create",
        "Create a ComfyUI matting batch in local SQLite. Fake mode: counts images, no GPU.",
        True,
        matting_skills.batch_create,
        {"input_dir": "string", "output_dir": "string optional", "note": "string optional"},
        partial=True,
        domain="matting",
        risk_level="write_safe",
        examples=[{
            "skill": "matting.batch_create",
            "arguments": {"input_dir": "E:\\assetclaw-matting-bot\\storage\\batch_inputs"},
        }],
        natural_language_examples=["用 E:\\assetclaw-matting-bot\\storage\\batch_inputs 创建一个抠图批次"],
    ),
    _skill(
        "matting.batch_start",
        "Start a matting batch. Fake mode: changes status only, no GPU.",
        True,
        matting_skills.batch_start,
        {"batch_id": "string"},
        partial=True,
        domain="matting",
        risk_level="write_safe",
        natural_language_examples=["启动批次 BATCH_XXXX"],
    ),
    _skill(
        "matting.batch_status",
        "Check matting batch status.",
        True,
        matting_skills.batch_status,
        {"batch_id": "string"},
        partial=True,
        domain="matting",
        risk_level="readonly",
        natural_language_examples=["查看批次 BATCH_XXXX 的状态"],
    ),
    _skill(
        "matting.batch_list",
        "List recent matting batches from DB.",
        True,
        matting_skills.batch_list,
        {"limit": "integer optional"},
        partial=True,
        domain="matting",
        risk_level="readonly",
        natural_language_examples=["列出所有抠图批次", "查看最近创建的批次"],
    ),
    _skill(
        "matting.batch_detail",
        "Get detail of a matting batch including image count.",
        True,
        matting_skills.batch_detail,
        {"batch_id": "string"},
        partial=True,
        domain="matting",
        risk_level="readonly",
        natural_language_examples=["查看批次 BATCH_XXXX 的详情"],
    ),
    _skill(
        "matting.batch_pause",
        "Pause a matting batch. Fake mode: changes status only.",
        True,
        matting_skills.batch_pause,
        {"batch_id": "string"},
        partial=True,
        domain="matting",
        risk_level="write_safe",
    ),
    _skill(
        "matting.batch_resume",
        "Resume a matting batch. Fake mode: changes status only.",
        True,
        matting_skills.batch_resume,
        {"batch_id": "string"},
        partial=True,
        domain="matting",
        risk_level="write_safe",
    ),
    _skill(
        "matting.batch_cancel",
        "Cancel a matting batch. Fake mode: changes status only.",
        True,
        matting_skills.batch_cancel,
        {"batch_id": "string"},
        partial=True,
        domain="matting",
        risk_level="write_safe",
    ),
    _skill(
        "matting.shared_start",
        "Copy images from an allowed shared drive input dir to local storage, run a ComfyUI workflow locally, report progress to Feishu, then sync outputs back to the shared drive.",
        True,
        shared_matting_skills.shared_matting_start,
        {
            "shared_input_dir": "string",
            "shared_output_dir": "string",
            "workflow_path": "string optional",
            "notify_interval_seconds": "integer optional",
            "max_images": "integer optional",
        },
        domain="matting",
        risk_level="write_safe",
        natural_language_examples=["把共享盘 input0529 用抠图 workflow 跑一遍，结果同步到 output0529"],
    ),
    _skill(
        "matting.shared_status",
        "Show shared-drive matting progress, local staging dirs, shared input/output dirs, ComfyUI progress, ETA and GPU status.",
        True,
        shared_matting_skills.shared_matting_status,
        {"run_id": "string optional"},
        domain="matting",
        risk_level="readonly",
        natural_language_examples=["共享盘抠图任务现在跑到哪里了"],
    ),
    _skill(
        "matting.shared_sync_outputs",
        "Manually sync local ComfyUI outputs back to the shared-drive output directory.",
        True,
        shared_matting_skills.shared_matting_sync_outputs,
        {"run_id": "string"},
        domain="matting",
        risk_level="write_safe",
        natural_language_examples=["把这个共享盘抠图任务的结果同步回共享盘"],
    ),
    # ---- queue / comfyui ----------------------------------------------------
    _skill(
        "queue.status",
        "Return queue status stub.",
        True,
        queue_skills.queue_status,
        partial=True,
        domain="queue",
        risk_level="readonly",
    ),
    _skill(
        "matting_pipeline.status",
        "Show the current GitLab-managed matting pipeline repo commit, update time, ComfyUI workflow path, and linked assets.",
        True,
        matting_pipeline_skills.status,
        domain="matting_pipeline",
        risk_level="readonly",
        natural_language_examples=[
            "现在用的抠图管线是什么",
            "当前抠图管线版本",
            "抠图管线什么时候更新的",
            "现在 ImageClip 是哪个 commit",
        ],
    ),
    _skill(
        "matting_pipeline.verify",
        "Verify the GitLab-managed matting pipeline repo assets, ComfyUI links/copies, and workflow JSON parseability.",
        True,
        matting_pipeline_skills.verify,
        domain="matting_pipeline",
        risk_level="readonly",
        natural_language_examples=["验证抠图管线", "检查 ImageClip 管线有没有问题", "校验当前抠图工作流"],
    ),
    _skill(
        "matting_pipeline.update",
        "Clone or pull the GitLab ImageClip pipeline repo, then sync workflow, lora, and Cherry_lizi into the Aki ComfyUI runtime via symlink with copy fallback.",
        False,
        matting_pipeline_skills.update,
        {"force_copy": "boolean optional"},
        domain="matting_pipeline",
        risk_level="write_safe",
        requires_confirmation=False,
        natural_language_examples=["更新抠图管线", "拉最新 ImageClip", "同步最新 ComfyUI 抠图工作流"],
    ),
    _skill(
        "comfyui.status",
        "Check ComfyUI configured URL, fake mode, workflow path, and /system_stats reachability.",
        True,
        status_skills.comfyui_status,
        domain="comfyui",
        risk_level="readonly",
        natural_language_examples=["ComfyUI 状态", "查看 ComfyUI 是否在线", "现在显卡使用情况怎么样"],
    ),
    _skill(
        "comfyui.workflows",
        "List local ComfyUI workflow json files.",
        True,
        comfyui_skills.workflows_list,
        {"path": "string optional", "max_results": "integer optional"},
        domain="comfyui",
        risk_level="readonly",
        natural_language_examples=["列出当前有哪些 ComfyUI 工作流"],
    ),
    _skill(
        "comfyui.workflow_info",
        "Inspect the selected or specified ComfyUI API workflow: nodes, LoadImage nodes, SaveImage nodes.",
        True,
        comfyui_skills.workflow_info,
        {"path": "string optional"},
        domain="comfyui",
        risk_level="readonly",
        natural_language_examples=["查看当前抠图 workflow 的节点信息"],
    ),
    _skill(
        "comfyui.run_preview",
        "Preview a ComfyUI batch run before confirmation: workflow, input/output dirs, image count, and key nodes.",
        True,
        comfyui_skills.run_preview,
        {
            "workflow_path": "string optional",
            "input_dir": "string optional",
            "output_dir": "string optional",
            "recursive": "boolean optional",
            "preserve_structure": "boolean optional",
            "max_images": "integer optional",
        },
        domain="comfyui",
        risk_level="readonly",
        natural_language_examples=["预览 E:\\input 到 E:\\output 的抠图任务"],
    ),
    _skill(
        "comfyui.workflow_select",
        "Select a ComfyUI workflow json for the current conversation; later run_start can omit workflow_path.",
        True,
        comfyui_skills.workflow_select,
        {"path": "string"},
        domain="comfyui",
        risk_level="write_safe",
        natural_language_examples=["选择软边缘测试-动画批量.json 作为抠图管线"],
    ),
    _skill(
        "comfyui.queue_status",
        "Read ComfyUI native /queue status.",
        True,
        comfyui_skills.queue_status,
        {},
        domain="comfyui",
        risk_level="readonly",
        natural_language_examples=["ComfyUI 队列里现在在跑什么"],
    ),
    _skill(
        "comfyui.run_start",
        "Submit a ComfyUI workflow for all images in an input directory and track the run.",
        True,
        comfyui_skills.run_start,
        {
            "workflow_path": "string optional",
            "input_dir": "string",
            "output_dir": "string",
            "input_node_id": "string optional",
            "input_name": "string optional",
            "max_images": "integer optional",
            "recursive": "boolean optional",
            "preserve_structure": "boolean optional",
            "skip_existing": "boolean optional",
            "priority_characters": "array optional",
            "notify_interval_seconds": "integer optional",
        },
        domain="comfyui",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["开始批量抠图，输入 E:\\input，输出 E:\\output，保留目录结构"],
    ),
    _skill(
        "comfyui.run_pause",
        "Pause a tracked ComfyUI batch run after the current image finishes; future images will not be submitted.",
        True,
        comfyui_skills.run_pause,
        {"run_id": "string optional"},
        domain="comfyui",
        risk_level="write_safe",
        natural_language_examples=["暂停当前抠图任务", "先停一下后续抠图"],
    ),
    _skill(
        "comfyui.run_resume",
        "Resume a paused ComfyUI batch run.",
        True,
        comfyui_skills.run_resume,
        {"run_id": "string optional"},
        domain="comfyui",
        risk_level="write_safe",
        natural_language_examples=["继续刚才的抠图任务"],
    ),
    _skill(
        "comfyui.run_cancel",
        "Cancel a tracked ComfyUI batch run and stop future images; optionally interrupt current ComfyUI execution.",
        True,
        comfyui_skills.run_cancel,
        {"run_id": "string optional", "interrupt_current": "boolean optional", "notify": "boolean optional"},
        domain="comfyui",
        risk_level="write_caution",
        requires_confirmation=False,
        natural_language_examples=["终止当前抠图任务", "取消这个 ComfyUI 任务"],
    ),
    _skill(
        "comfyui.run_delete",
        "Archive a finished, failed, or canceled tracked ComfyUI run so it no longer appears in normal task lists.",
        True,
        comfyui_skills.run_delete,
        {"run_id": "string optional"},
        domain="comfyui",
        risk_level="write_safe",
        natural_language_examples=["删除这个失败的 ComfyUI 任务记录", "把已取消的任务从列表里清掉"],
    ),
    _skill(
        "comfyui.run_status",
        "Show the latest or specified ComfyUI run progress, input/output dirs, ETA, queue and GPU status.",
        True,
        comfyui_skills.run_status,
        {"run_id": "string optional", "include_gpu": "boolean optional"},
        domain="comfyui",
        risk_level="readonly",
        natural_language_examples=["现在 ComfyUI 跑到多少张了", "当前管线输入输出目录是什么"],
    ),
    _skill(
        "comfyui.run_list",
        "List recent ComfyUI runs with workflow, input/output dirs, status and progress.",
        True,
        comfyui_skills.run_list,
        {"limit": "integer optional", "include_archived": "boolean optional", "include_finished": "boolean optional"},
        domain="comfyui",
        risk_level="readonly",
        natural_language_examples=["我们现在有哪些 ComfyUI 任务", "列出当前抠图和平滑任务"],
    ),
    _skill(
        "comfyui.run_update",
        "Update workflow/input/output options for a queued or paused ComfyUI run.",
        True,
        comfyui_skills.run_update,
        {
            "run_id": "string optional",
            "workflow_path": "string optional",
            "input_dir": "string optional",
            "output_dir": "string optional",
            "recursive": "boolean optional",
            "preserve_structure": "boolean optional",
            "max_images": "integer optional",
        },
        domain="comfyui",
        risk_level="write_safe",
        natural_language_examples=["把后面那个任务的输入路径改成 E:\\input2", "把这个任务改用另一个工作流"],
    ),
    _skill(
        "comfyui.run_sync_outputs",
        "Download completed ComfyUI outputs for a tracked run into its configured output directory.",
        True,
        comfyui_skills.run_sync_outputs,
        {"run_id": "string", "overwrite": "boolean optional"},
        domain="comfyui",
        risk_level="write_safe",
        natural_language_examples=["同步这个 ComfyUI 任务的输出结果"],
    ),
    # ---- Cherry frame sequence processing ----------------------------------
    _skill(
        "cherry.info",
        "Show Cherry frame-sequence processing tool path, availability, steps and defaults.",
        True,
        cherry_skills.info,
        {},
        domain="cherry",
        risk_level="readonly",
        natural_language_examples=["Cherry 帧序列工具状态", "这个平滑工具默认参数是什么"],
    ),
    _skill(
        "cherry.run_preview",
        "Preview a Cherry frame sequence batch run: input/output dirs, image count, sequence groups and options.",
        True,
        cherry_skills.run_preview,
        {"input_dir": "string", "output_dir": "string", "recursive": "boolean optional", "max_images": "integer optional"},
        domain="cherry",
        risk_level="readonly",
        natural_language_examples=["预览 E:\\output 到 E:\\smooth_output 的 Cherry 平滑任务"],
    ),
    _skill(
        "cherry.run_start",
        "Run Cherry post-processing on all images under an input directory, preserving folder structure. The main chain is denoise, blur-under-composite, resize/sharpen twice; temporal alpha smoothing is optional and off by default.",
        True,
        cherry_skills.run_start,
        {
            "input_dir": "string",
            "output_dir": "string",
            "recursive": "boolean optional",
            "max_images": "integer optional",
            "skip_existing": "boolean optional",
            "notify_interval_seconds": "integer optional",
            "use_denoise": "boolean optional",
            "denoise_threshold": "number optional",
            "denoise_radius": "integer optional",
            "use_shadow": "boolean optional",
            "shadow_gray_limit": "number optional",
            "shadow_protect_radius": "integer optional",
            "shadow_alpha_boost": "number optional",
            "use_blur": "boolean optional",
            "blur_radius": "integer optional",
            "blur_sigma": "number optional",
            "use_resize1": "boolean optional",
            "resize1_width": "integer optional",
            "resize1_height": "integer optional",
            "use_sharp1": "boolean optional",
            "sharp1_amount": "number optional",
            "sharp1_radius": "integer optional",
            "sharp1_threshold": "number optional",
            "sharp1_shrink": "integer optional",
            "use_resize2": "boolean optional",
            "resize2_width": "integer optional",
            "resize2_height": "integer optional",
            "use_sharp2": "boolean optional",
            "sharp2_amount": "number optional",
            "sharp2_radius": "integer optional",
            "sharp2_threshold": "number optional",
            "sharp2_shrink": "integer optional",
            "use_smooth": "boolean optional",
            "smooth_window": "integer optional",
            "smooth_sigma": "number optional",
            "min_alpha": "number optional",
            "sync_rgb": "boolean optional",
            "use_resize": "boolean optional",
            "resize_width": "integer optional",
            "resize_height": "integer optional",
            "use_sharpen": "boolean optional",
            "sharpen_amount": "number optional",
            "sharpen_radius": "integer optional",
            "sharpen_threshold": "number optional",
            "sharpen_shrink": "integer optional",
        },
        domain="cherry",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["对 E:\\output 做 Cherry 平滑处理，输出到 E:\\smooth_output"],
    ),
    _skill(
        "cherry.run_status",
        "Show latest or specified Cherry task progress, input/output dirs, ETA and GPU status.",
        True,
        cherry_skills.run_status,
        {"run_id": "string optional", "include_gpu": "boolean optional"},
        domain="cherry",
        risk_level="readonly",
        natural_language_examples=["Cherry 平滑任务跑到哪里了", "现在帧序列处理进度怎么样"],
    ),
    _skill(
        "cherry.run_list",
        "List recent Cherry frame sequence processing runs.",
        True,
        cherry_skills.run_list,
        {"limit": "integer optional", "include_archived": "boolean optional", "include_finished": "boolean optional"},
        domain="cherry",
        risk_level="readonly",
        natural_language_examples=["我们现在有哪些 Cherry 任务", "列出当前平滑任务"],
    ),
    _skill(
        "cherry.run_cancel",
        "Cancel a tracked Cherry run and stop future sequence groups.",
        True,
        cherry_skills.run_cancel,
        {"run_id": "string optional"},
        domain="cherry",
        risk_level="write_safe",
        natural_language_examples=["终止当前 Cherry 任务", "取消这个平滑任务"],
    ),
    _skill(
        "cherry.run_delete",
        "Archive a finished, failed, or canceled Cherry run so it no longer appears in normal task lists.",
        True,
        cherry_skills.run_delete,
        {"run_id": "string optional"},
        domain="cherry",
        risk_level="write_safe",
        natural_language_examples=["删除这个 Cherry 任务记录", "把已取消的平滑任务清掉"],
    ),
    # ---- Animation production operations -----------------------------------
    _skill(
        "animation.status",
        "Inspect an animation automation workspace: videos, extracted frames, matte outputs, smooth outputs, backups and active runs.",
        True,
        animation_ops_skills.status,
        {"root": "string optional", "include_runs": "boolean optional"},
        domain="animation",
        risk_level="readonly",
        natural_language_examples=[
            "看一下 E:\\animation_automation\\2026-06-02 动画流程现在有多少帧",
            "动画自动化目录当前状态",
            "matte 和 smooth 数量对不对",
        ],
    ),
    _skill(
        "animation.manual_smooth_current",
        "Run the latest Cherry smoothing model on the current matte directory and write to the smooth directory, preserving structure.",
        True,
        animation_ops_skills.manual_smooth_current,
        {
            "root": "string optional",
            "input_dir": "string optional",
            "output_dir": "string optional",
            "skip_existing": "boolean optional",
            "notify_interval_seconds": "integer optional",
            "use_smooth": "boolean optional",
            "resize_width": "integer optional",
            "resize_height": "integer optional",
        },
        domain="animation",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=[
            "基于 E:\\animation_automation\\2026-06-02\\matte 再做一次平滑，输出到 smooth",
            "对当前动画 matte 重新跑最新 Cherry 平滑",
        ],
    ),
    _skill(
        "animation.rerun_from_videos",
        "Archive existing animation outputs, re-extract every frame from videos at 24 fps by duration, then run ComfyUI matting and Cherry smoothing.",
        True,
        animation_ops_skills.rerun_from_videos,
        {
            "root": "string optional",
            "fps": "integer optional",
            "workflow_path": "string optional",
            "poll_seconds": "integer optional",
            "extract_only": "boolean optional",
        },
        domain="animation",
        risk_level="write_caution",
        requires_confirmation=True,
        natural_language_examples=[
            "E:\\animation_automation\\2026-06-02 从 videos 全部重抽帧重新抠图和平滑",
            "动画流程全部重做，输入是 E:\\animation_automation\\2026-06-02",
        ],
    ),
    _skill(
        "unity_ready.preview",
        "Preview unity_ready output paths and package readiness for scene/emoji/story without writing files.",
        True,
        unity_ready_skills.preview,
        {
            "date_root": "string optional",
            "copy_mode": "string optional",
        },
        domain="unity_ready",
        risk_level="readonly",
        natural_language_examples=["预览 unity_ready 整理", "检查第 5 步 unity_ready 输出"],
    ),
    _skill(
        "unity_ready.build",
        "Build unity_ready/scene, unity_ready/emoji, and unity_ready/story manifests and frames from the current animation workspace.",
        True,
        unity_ready_skills.build,
        {
            "date_root": "string optional",
            "overwrite": "boolean optional",
            "copy_mode": "string optional",
        },
        domain="unity_ready",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["单独执行 unity_ready 整理", "生成第 5 步 unity_ready"],
    ),
    _skill(
        "unity_ready.status",
        "Show unity_ready scene/emoji/story package paths, JSON existence and frame counts.",
        True,
        unity_ready_skills.status,
        {"date_root": "string optional"},
        domain="unity_ready",
        risk_level="readonly",
        natural_language_examples=["unity_ready 状态", "第 5 步整理好了没"],
    ),
    _skill(
        "unity_import.preview",
        "Preview Unity AnimTextureImporter inputs from unity_ready and verify Unity MCP/API availability. Never clicks the Unity UI.",
        True,
        unity_import_skills.preview,
        {
            "unity_ready": "string",
            "unity_project": "string optional",
            "package": "string optional",
            "mode": "string optional",
            "import_mode": "string optional",
            "mcp_url": "string optional",
        },
        domain="unity",
        risk_level="readonly",
        natural_language_examples=["预览 unity_ready 导入路径", "检查 Unity MCP 能不能导入动画资源"],
    ),
    _skill(
        "unity_import.run",
        "Run Unity AnimTextureImporter through API/MCP only by creating a temporary auto-deleted Unity editor runner. It does not click UI or modify plugin source.",
        True,
        unity_import_skills.run_import,
        {
            "unity_ready": "string",
            "unity_project": "string optional",
            "package": "string optional",
            "mode": "string optional",
            "import_mode": "string optional",
            "mcp_url": "string optional",
        },
        domain="unity",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["通过 Unity MCP 导入 unity_ready 动画资源"],
    ),
    _skill(
        "unity_import.status",
        "Show Unity import readiness and MCP/API status for a unity_ready folder.",
        True,
        unity_import_skills.status,
        {
            "unity_ready": "string",
            "unity_project": "string optional",
            "package": "string optional",
            "mode": "string optional",
            "import_mode": "string optional",
            "mcp_url": "string optional",
        },
        domain="unity",
        risk_level="readonly",
        natural_language_examples=["Unity 导入状态", "Unity MCP 状态"],
    ),
    _skill(
        "unity_tools.atlas_status",
        "Read the latest Unity sprite atlas size report JSON and Unity MCP status without generating a new report.",
        True,
        unity_tools_skills.atlas_status,
        {"unity_project": "string optional", "mcp_url": "string optional"},
        domain="unity",
        risk_level="readonly",
        natural_language_examples=["查看图集大小报告", "AtlasSizeReport 状态", "看看 Unity 图集统计结果"],
    ),
    _skill(
        "unity_tools.atlas_report",
        "Run Unity SpriteAtlasGeneratorTool.DoGenerate to generate Assets/TATest/AtlasSizeReport.json. Standalone only; not part of animation_flow.",
        True,
        unity_tools_skills.atlas_report,
        {"unity_project": "string optional", "mcp_url": "string optional", "timeout_seconds": "integer optional"},
        domain="unity",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["生成图集大小报告", "跑一下预打图集统计", "检查 SpriteAtlas 资源大小"],
    ),
    _skill(
        "unity_tools.rename_preview",
        "Preview Unity AnimTextureBatchRename results for a texture folder and animation folder without applying renames.",
        True,
        unity_tools_skills.rename_preview,
        {
            "texture_folder": "string",
            "animation_folder": "string",
            "unity_project": "string optional",
            "mcp_url": "string optional",
            "timeout_seconds": "integer optional",
        },
        domain="unity",
        risk_level="readonly",
        natural_language_examples=["预览动画贴图批量重命名", "检查贴图命名整理会改哪些文件"],
    ),
    _skill(
        "unity_tools.rename_run",
        "Run Unity AnimTextureBatchRename for a texture folder and animation folder after scanning errors. Standalone only; not part of animation_flow.",
        True,
        unity_tools_skills.rename_run,
        {
            "texture_folder": "string",
            "animation_folder": "string",
            "unity_project": "string optional",
            "mcp_url": "string optional",
            "timeout_seconds": "integer optional",
        },
        domain="unity",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["执行动画贴图批量重命名", "整理这个角色动画贴图命名", "跑 AnimTextureBatchRename"],
    ),
    _skill(
        "animation_flow.preview",
        "Preview the full 7-stage animation automation flow: Feishu download, frame extraction, ComfyUI matting, Cherry smoothing, unity_ready, Unity import, P4 shelve plan.",
        True,
        animation_flow_skills.run_preview,
        {
            "date_root": "string optional",
            "unity_project": "string optional",
            "p4_workflow": "string optional",
            "p4_workspace": "string optional",
            "p4_stream": "string optional",
            "package": "string optional",
            "unity_import_mode": "string optional",
            "import_mode": "string optional",
            "fake_matting_from_frames": "boolean optional",
            "priority_characters": "array optional",
        },
        domain="animation_flow",
        risk_level="readonly",
        natural_language_examples=["预览完整动画自动化流程", "看一下 7 步动画流程计划", "动画自动化 2026-06-10 导入预览"],
    ),
    _skill(
        "animation_flow.start",
        "Start the full 7-stage animation automation flow, including Cherry smoothing, Unity import and P4 create-cl/reconcile/shelve/report. Submit is disabled.",
        True,
        animation_flow_skills.run_start,
        {
            "date_root": "string optional",
            "workflow_path": "string optional",
            "unity_project": "string optional",
            "p4_workflow": "string optional",
            "p4_workspace": "string optional",
            "p4_stream": "string optional",
            "package": "string optional",
            "unity_import_mode": "string optional",
            "import_mode": "string optional",
            "fps": "integer optional",
            "notify_interval_seconds": "integer optional",
            "allow_p4_writes": "boolean optional",
            "fake_matting_from_frames": "boolean optional",
            "priority_characters": "array optional",
        },
        domain="animation_flow",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["开始这个动画自动化流程", "启动完整动画自动化流程", "动画自动化20260610 迭代"],
    ),
    _skill(
        "animation_flow.status",
        "Show full 7-stage animation flow progress and nested run IDs.",
        True,
        animation_flow_skills.run_status,
        {"run_id": "string optional"},
        domain="animation_flow",
        risk_level="readonly",
        natural_language_examples=["完整动画流程到哪了", "7 步动画自动化流程进度"],
    ),
    _skill(
        "animation_flow.resume",
        "Resume a blocked full animation flow from the confirmed Unity import result and continue P4 create-cl/reconcile/shelve/report. Submit is disabled.",
        True,
        animation_flow_skills.run_resume,
        {"run_id": "string optional"},
        domain="animation_flow",
        risk_level="write_safe",
        requires_confirmation=False,
        natural_language_examples=["继续动画自动化 AFLOW_xxx", "恢复完整动画流程", "从 P4 继续这个动画自动化任务"],
    ),
    _skill(
        "animation_flow.list",
        "List active or recent 7-stage animation flow runs.",
        True,
        animation_flow_skills.run_list,
        {"limit": "integer optional", "include_finished": "boolean optional"},
        domain="animation_flow",
        risk_level="readonly",
        natural_language_examples=["现在有哪些完整动画流程任务"],
    ),
    _skill(
        "animation_flow.cancel",
        "Cancel the active 7-stage animation flow and its child runs if present.",
        True,
        animation_flow_skills.run_cancel,
        {"run_id": "string optional"},
        domain="animation_flow",
        risk_level="write_safe",
        natural_language_examples=["取消完整动画自动化流程"],
    ),
    _skill(
        "direct_video.start",
        "Process Feishu-uploaded video attachments directly: copy originals, extract frames, run ComfyUI matting, run Cherry post-processing, zip all four parts, and send the zip back to the current Feishu chat.",
        True,
        direct_video_skills.start,
        {
            "video_paths": "array[string]",
            "source_names": "array[string] optional",
            "fps": "integer optional",
            "max_frames": "integer optional",
            "workflow_path": "string optional",
            "notify_interval_seconds": "integer optional",
        },
        domain="direct_video",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["我发了视频，开始动画处理", "处理这个动画视频", "把这个视频抽帧抠图后处理并打包发我"],
    ),
    _skill(
        "direct_video.status",
        "Show progress for the latest or specified direct Feishu video processing run.",
        True,
        direct_video_skills.status,
        {"run_id": "string optional"},
        domain="direct_video",
        risk_level="readonly",
        natural_language_examples=["动画处理进度", "这个视频处理到哪了", "直传视频任务状态"],
    ),
    _skill(
        "direct_video.list",
        "List direct Feishu video processing runs.",
        True,
        direct_video_skills.list_runs,
        {"limit": "integer optional", "include_finished": "boolean optional"},
        domain="direct_video",
        risk_level="readonly",
        natural_language_examples=["有哪些视频处理任务", "列出直传视频任务"],
    ),
    _skill(
        "direct_video.resend_zip",
        "Resend an already generated direct-video zip to the original Feishu chat without rerunning frame extraction, matting, or post-processing.",
        True,
        direct_video_skills.resend_zip,
        {"run_id": "string optional"},
        domain="direct_video",
        risk_level="egress_caution",
        requires_confirmation=False,
        natural_language_examples=["重发这个视频处理 zip", "把直传视频结果 zip 再发一次", "重发 VID_xxx 的 zip"],
    ),
    _skill(
        "direct_video.cancel",
        "Cancel a direct Feishu video processing run.",
        True,
        direct_video_skills.cancel,
        {"run_id": "string optional"},
        domain="direct_video",
        risk_level="write_safe",
        requires_confirmation=False,
        natural_language_examples=["取消这个视频处理任务", "停止直传视频任务"],
    ),
    _skill(
        "direct_image.start",
        "Process Feishu-uploaded image attachments directly: run ComfyUI matting, run Cherry post-processing, and send final images back as file attachments.",
        True,
        direct_image_skills.start,
        {
            "image_paths": "array[string]",
            "source_names": "array[string] optional",
            "workflow_path": "string optional",
            "notify_interval_seconds": "integer optional",
        },
        domain="direct_image",
        risk_level="write_safe",
        requires_confirmation=False,
        natural_language_examples=["处理这张图片", "图片抠图后处理发回来", "把这些图片处理完用附件发我"],
    ),
    _skill(
        "direct_image.status",
        "Show progress for the latest or specified direct Feishu image processing run.",
        True,
        direct_image_skills.status,
        {"run_id": "string optional"},
        domain="direct_image",
        risk_level="readonly",
        natural_language_examples=["图片处理进度", "这张图处理到哪了"],
    ),
    _skill(
        "direct_image.list",
        "List direct Feishu image processing runs.",
        True,
        direct_image_skills.list_runs,
        {"limit": "integer optional", "include_finished": "boolean optional"},
        domain="direct_image",
        risk_level="readonly",
        natural_language_examples=["有哪些图片处理任务", "列出直传图片任务"],
    ),
    _skill(
        "direct_image.cancel",
        "Cancel a direct Feishu image processing run.",
        True,
        direct_image_skills.cancel,
        {"run_id": "string optional"},
        domain="direct_image",
        risk_level="write_safe",
        natural_language_examples=["取消这个图片处理任务", "停止直传图片任务"],
    ),
    _skill(
        "direct_image.resume_postprocess",
        "Resume a direct image run from existing ComfyUI matte outputs, then run Cherry post-processing and send final images as file attachments.",
        True,
        direct_image_skills.resume_from_postprocess,
        {"run_id": "string optional"},
        domain="direct_image",
        risk_level="write_safe",
        requires_confirmation=False,
        natural_language_examples=["继续这个图片处理任务", "从抠图结果继续图片后处理"],
    ),
    # ---- Feishu frame extraction and animation pipeline ---------------------
    _skill(
        "feishu_table.export_json",
        "Export the configured Feishu bitable to a JSON file, preserving field schema and records while excluding parent-record fields and keeping video attachment names only.",
        True,
        feishu_table_skills.export_json,
        {"table_url": "string optional", "output_path": "string optional", "config_path": "string optional"},
        domain="feishu_table",
        risk_level="write_safe",
        natural_language_examples=["导出飞书表格为 JSON", "把动画表格读取成 json 文件"],
    ),
    _skill(
        "feishu_table.restore_plan",
        "Build a dry-run restore plan from an exported Feishu bitable JSON. It does not write to Feishu.",
        True,
        feishu_table_skills.restore_plan,
        {"json_path": "string optional", "plan_output_path": "string optional"},
        domain="feishu_table",
        risk_level="readonly",
        natural_language_examples=["检查这个飞书表格 JSON 能否还原", "生成 JSON 写回飞书的还原计划"],
    ),
    _skill(
        "frame.info",
        "Show Feishu frame extraction tool path, config summary, fps and output dirs.",
        True,
        frame_skills.info,
        {},
        domain="frame",
        risk_level="readonly",
        natural_language_examples=["抽帧工具状态", "飞书抽帧配置是什么"],
    ),
    _skill(
        "frame.run_preview",
        "Preview a Feishu bitable video download and frame extraction run.",
        True,
        frame_skills.run_preview,
        {
            "download_dir": "string optional",
            "export_dir": "string optional",
            "fps": "integer optional",
            "max_frames": "integer optional",
            "diff_threshold": "number optional",
            "dedup_enabled": "boolean optional",
            "dedup_renumber": "boolean optional",
            "root": "string optional",
            "emotions": "array optional",
            "types": "array optional",
            "progress_include": "array optional",
            "progress_exclude": "array optional",
            "priority_characters": "array optional",
        },
        domain="frame",
        risk_level="readonly",
        natural_language_examples=["预览飞书抽帧任务，输出到 E:\\output_frames"],
    ),
    _skill(
        "frame.run_start",
        "Read Feishu bitable records, download every video attachment, and extract PNG frames locally.",
        True,
        frame_skills.run_start,
        {
            "download_dir": "string optional",
            "export_dir": "string optional",
            "fps": "integer optional",
            "max_frames": "integer optional",
            "diff_threshold": "number optional",
            "dedup_enabled": "boolean optional",
            "dedup_renumber": "boolean optional",
            "root": "string optional",
            "emotions": "array optional",
            "types": "array optional",
            "progress_include": "array optional",
            "progress_exclude": "array optional",
            "priority_characters": "array optional",
            "notify_interval_seconds": "integer optional",
        },
        domain="frame",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["开始飞书抽帧，下载到 E:\\raw_videos，抽帧输出 E:\\output_frames"],
    ),
    _skill(
        "frame.run_status",
        "Show latest or specified frame extraction progress.",
        True,
        frame_skills.run_status,
        {"run_id": "string optional"},
        domain="frame",
        risk_level="readonly",
        natural_language_examples=["抽帧任务跑到哪里了"],
    ),
    _skill(
        "frame.run_list",
        "List active/recent frame extraction runs.",
        True,
        frame_skills.run_list,
        {"limit": "integer optional", "include_finished": "boolean optional", "include_archived": "boolean optional"},
        domain="frame",
        risk_level="readonly",
        natural_language_examples=["现在有哪些抽帧任务"],
    ),
    _skill(
        "frame.run_cancel",
        "Cancel a tracked frame extraction run.",
        True,
        frame_skills.run_cancel,
        {"run_id": "string optional"},
        domain="frame",
        risk_level="write_safe",
        natural_language_examples=["终止当前抽帧任务"],
    ),
    _skill(
        "custom_pipeline.module_catalog",
        "List configurable modules and exposed parameters for custom animation workflows.",
        True,
        custom_pipeline_skills.module_catalog,
        {},
        domain="custom_pipeline",
        risk_level="readonly",
        natural_language_examples=["列出可编排模块和参数", "自定义流程有哪些模块可以用"],
    ),
    _skill(
        "custom_pipeline.save_definition",
        "Save a custom workflow definition composed of allowed backend skill steps.",
        True,
        custom_pipeline_skills.save_definition,
        {"name": "string", "description": "string optional", "variables": "object optional", "steps": "array", "overwrite": "boolean optional"},
        domain="custom_pipeline",
        risk_level="write_safe",
        natural_language_examples=["保存一个自定义动画流程", "定义一个先抽帧再抠图再平滑的流程"],
    ),
    _skill(
        "custom_pipeline.list_definitions",
        "List saved custom workflow definitions.",
        True,
        custom_pipeline_skills.list_definitions,
        {},
        domain="custom_pipeline",
        risk_level="readonly",
        natural_language_examples=["列出自定义流程", "有哪些保存过的流程"],
    ),
    _skill(
        "custom_pipeline.get_definition",
        "Read one saved custom workflow definition.",
        True,
        custom_pipeline_skills.get_definition,
        {"name": "string"},
        domain="custom_pipeline",
        risk_level="readonly",
        natural_language_examples=["查看这个自定义流程详情"],
    ),
    _skill(
        "custom_pipeline.preview_definition",
        "Preview a custom workflow with variables rendered but without running it.",
        True,
        custom_pipeline_skills.preview_definition,
        {"name": "string optional", "definition": "object optional", "variables": "object optional"},
        domain="custom_pipeline",
        risk_level="readonly",
        natural_language_examples=["预览自定义流程参数", "把流程变量渲染出来看看"],
    ),
    _skill(
        "custom_pipeline.run_start",
        "Run a saved or ad-hoc custom workflow by executing allowed backend skill steps in order.",
        True,
        custom_pipeline_skills.run_start,
        {"name": "string optional", "definition": "object optional", "variables": "object optional"},
        domain="custom_pipeline",
        risk_level="write_safe",
        requires_confirmation=True,
        natural_language_examples=["执行这个自定义动画流程", "按我定义的步骤跑一遍"],
    ),
    _skill(
        "custom_pipeline.run_status",
        "Show custom workflow run status and per-step results.",
        True,
        custom_pipeline_skills.run_status,
        {"run_id": "string optional"},
        domain="custom_pipeline",
        risk_level="readonly",
        natural_language_examples=["自定义流程跑到哪一步了"],
    ),
    _skill(
        "custom_pipeline.run_list",
        "List custom workflow runs.",
        True,
        custom_pipeline_skills.run_list,
        {"limit": "integer optional", "include_finished": "boolean optional"},
        domain="custom_pipeline",
        risk_level="readonly",
        natural_language_examples=["列出自定义流程运行记录"],
    ),
    _skill(
        "custom_pipeline.run_cancel",
        "Cancel a custom workflow run between steps.",
        True,
        custom_pipeline_skills.run_cancel,
        {"run_id": "string"},
        domain="custom_pipeline",
        risk_level="write_safe",
        natural_language_examples=["取消这个自定义流程"],
    ),
    _skill(
        "system.gpu_status",
        "Read GPU status through nvidia-smi: memory, utilization, temperature, power.",
        True,
        status_skills.gpu_status,
        {},
        domain="system",
        risk_level="readonly",
        natural_language_examples=["现在显卡使用情况怎么样", "nvidia-smi 结果", "GPU 显存占用"],
    ),
    _skill(
        "system.process_status",
        "List matching local processes. Read-only status check.",
        True,
        status_skills.process_status,
        {"names": "list[string] optional"},
        domain="system",
        risk_level="readonly",
        natural_language_examples=["看看 ComfyUI 进程在不在", "查看 python 进程"],
    ),
    # ---- reserved / not implemented ----------------------------------------
    _skill(
        "log.tail",
        "Reserved sanitized log tail skill. Not yet implemented.",
        False,
        future_skills.not_implemented,
        domain="logs",
        risk_level="readonly",
    ),
]

_MAP = {item["name"]: item for item in SKILLS}


def get_skill_meta(skill_name: str) -> dict[str, Any] | None:
    item = _MAP.get(skill_name)
    if not item:
        return None
    return {k: v for k, v in item.items() if k != "fn"}


def get_manifest() -> dict[str, Any]:
    from assetclaw_matting.config import settings

    return {
        "name": "AssetClaw Win3090 Animation Butler",
        "worker_id": settings.worker_id,
        "agent_runs_on_gpu": settings.agent_runs_on_gpu,
        "skills": [{k: v for k, v in item.items() if k != "fn"} for item in SKILLS],
    }


def call_skill(skill_name: str, arguments: dict[str, Any], requested_by: str = "brain") -> dict[str, Any]:
    from assetclaw_matting.db.repos import insert_skill_call

    request_id = str(uuid.uuid4())
    item = _MAP.get(skill_name)
    if not item:
        result = {"ok": False, "skill": skill_name, "error": f"unknown skill: {skill_name}"}
        insert_skill_call(request_id, skill_name, arguments, result, False, result["error"], requested_by)
        return result

    try:
        if not item["implemented"]:
            result = {"ok": False, "skill": skill_name, "error": "not implemented", "implemented": False}
        else:
            payload = item["fn"](**(arguments or {}))
            if isinstance(payload, dict) and payload.get("ok") is False:
                result = {"ok": False, "skill": skill_name, "error": payload.get("error", "skill returned ok=false"), "result": payload}
            else:
                result = {"ok": True, "skill": skill_name, "result": payload}
        insert_skill_call(request_id, skill_name, arguments, result, bool(result.get("ok")), result.get("error"), requested_by)
        return result
    except Exception as exc:
        error = redact_secrets(exc)
        log.warning("skill %s failed: %s", skill_name, error)
        result = {"ok": False, "skill": skill_name, "error": error}
        insert_skill_call(request_id, skill_name, arguments, result, False, error, requested_by)
        return result
